# Generated by Django 4.1.2 on 2022-11-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
    ]
