# Generated by Django 4.1.2 on 2022-11-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='null', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
