# Generated by Django 4.1.2 on 2022-11-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='username',
        ),
    ]
