# Generated by Django 4.1.2 on 2022-11-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_rename_name_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
